power <- read.table("household_power_consumption.txt", sep =";", header = TRUE)
power_sub <- subset(power, Date == "1/2/2007"|Date == "2/2/2007")
power_sub$Posix <- paste(power_sub$Date,power_sub$Time)
power_sub$Posix <- strptime(power_sub$Posix, format = "%d/%m/%Y %H:%M:%S")
power_sub$Sub_metering_1 <- as.numeric(as.character(power_sub$Sub_metering_1))
power_sub$Sub_metering_2 <- as.numeric(as.character(power_sub$Sub_metering_2))
power_sub$Sub_metering_3 <- as.numeric(as.character(power_sub$Sub_metering_3))
plot(power_sub$Posix, power_sub$Sub_metering_1, type = "l", lty = 1, xlab = "", ylab = "Energy sub metering")
lines(power_sub$Posix, power_sub$Sub_metering_2, type = "l", lty = 1, col = "red")
lines(power_sub$Posix, power_sub$Sub_metering_3, type = "l", lty = 1, col = "blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty = 1,cex = 0.8,y.intersp=0.5)
dev.copy(png,"plot3.png")
dev.off()